name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  issues: write

env:
  APP_LOCATION: "/"
  API_LOCATION: "api"
  OUTPUT_LOCATION: "build"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build and Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ 7b479af72d28b61fbd5f2305c6532b13d1c836afde34ab4a6da1ea43201a7e4902-739ed393-c0e2-4003-8f6b-f4af253c9ab000330290fbfebd03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          output_location: ${{ env.OUTPUT_LOCATION }}